#! /bin/sh -e
source "$(dirname "$0")"/_/env.source.sh

if test "$1" = '--help'; then echo "\
Usage:
  $0
  $0 --help

  We’ll build the lot with elm-make and elm-css.
"; exit; fi
set -x

git clean -dXf public/

"$local"/webpack
"$scripts"/styles
