#! /bin/sh -e
private="$(dirname "$0")"/_
source "$private"/env.source.sh

if test "$1" = '--help'; then echo "\
Usage:
  $0
  $0 --help

  We’ll build the lot with elm-make.
"; exit; fi
set -x

"$local"/elm-make \
  $(cat "$private"/elm-make-args.txt)
