#! /bin/sh -ex
source "$(dirname "$0")"/_/env.source.sh

"$scripts"/build

mkdir -p "$build_artifacts"
rm -rf "$build_artifacts"/deploy
cp -r public "$build_artifacts"/deploy
rm "$build_artifacts"/deploy/polymer

"$local"/vulcanize public/polymer.html \
  > "$build_artifacts"/deploy/polymer.html

"$local"/surge \
  --project="$build_artifacts"/deploy/ \
  --domain=https://parametric-svg.surge.sh
