#! /bin/sh -e
source "$(dirname "$0")"/_/env.source.sh

if test "$1" = '--help'; then echo "\
Usage:
  $0 [...<npm args>]
  $0 --help

  This is a proxy to npm. We’ll call \`npm shrinkwrap\` afterwards.
"; exit; fi
set -x

mkdir -p "$build_artifacts"/npm
if test -e node_modules/@polymer/web-animations-js; then
  mv node_modules/@polymer/web-animations-js "$build_artifacts"/npm/
fi

"$local"/npm $@
"$local"/npm shrinkwrap --dev

mv "$build_artifacts"/npm/web-animations-js node_modules/@polymer/

set +x
read \
  -p 'Would you like us to commit any updated dependencies? [y/n] ' \
  -n 1 \
  reply
echo
if test "$reply" = 'y'; then
  git commit -m '[scripts/npm] Update dependencies' \
    package.json \
    npm-shrinkwrap.json
fi
set -x
