#! /bin/sh -e
private="$(dirname "$0")"/_
source "$private"/env.source.sh

if test "$1" = '--help'; then echo "\
Usage:
  $0 [--open]
  $0 --help

  We’ll run a preconfifured elm-live server at http://localhost:9229.
"; exit; fi
set -x

"$local"/elm-live \
  $(cat "$private"/elm-make-args.txt) \
  --path-to-elm-make=node_modules/.bin/elm-make \
  --port=9229 \
  --host=0.0.0.0 \
  --dir=public/ \
  $@
