#! /bin/sh -e
source "$(dirname "$0")"/_/env.source.sh

if test "$1" = '--help'; then echo "\
Usage:
  $0 [--open]
  $0 --help

  We’ll run a preconfifured webpack dev server at http://localhost:9229.
  We’re not watching your CSS, so make sure you run \`styles\`
  any time you change those.
"; exit; fi
set -x

"$local"/webpack-dev-server \
  --path-to-elm-make=node_modules/.bin/elm-make \
  --port=9229 \
  --host=0.0.0.0 \
  --content-base=public/ \
  --inline \
  --history-api-fallback \
  $@
