#! /bin/sh -e
source "$(dirname "$0")"/_/env.source.sh

if test "$1" = '--help'; then echo "\
Usage:
  We’ll run a preconfifured webpack-dev-server at http://localhost:9111.

  $0 [...<webpack-dev-server args>]
  $0 --help
"; exit; fi
set -x

"$local"/webpack-dev-server \
  --port=9111 \
  --host=0.0.0.0 \
  --history-api-fallback \
  --content-base=public/ \
  --inline \
  $@
